# GET http://localhost:4000/api/v1/books

# GET http://localhost:4000/api/v1/books/1


POST http://localhost:4000/api/v1/books/add HTTP/1.1
content-type: application/json

{ 
    "title":"Harry Potter and the Sorcerer's Stone",
    "author": "J.K. Rowling",
    "genre": "Fantasy",
    "year": 1997
}